### PR TITLE
Update gem to dump and parse enum values with spaces correctly

### LINKED ISSUE #3: Schema dumper assumes that enum values will not contain spaces
Hi 👋 

I've been using `activerecord-pg_enum` for a few weeks now, it's a fantastic gem, thanks for writing it.

Today I was adding a migration to create an enum which has values containing spaces, but the dumper doesn't appear to handle this correctly.

I've been taking a look at the codebase and would be happy to try and make this change, assuming it's deemed valid.

# Steps to reproduce

**Rails version:** 5.2.2.1
**Ruby version:** 2.6.3
**activerecord-pg_enum version:** 1.0.2

## Migration
```ruby
# frozen_string_literal: true
​
class AddStatusEnum < ActiveRecord::Migration[5.2]
  def up
    create_enum 'status', ['sick', 'on vacation', 'working from home']
  end
​
  def down
    drop_enum 'status'
  end
end
```
### Expected Schema
```ruby
ActiveRecord::Schema.define(version: 2019_09_27_145140) do
  # ...

  # These are custom enum types that must be created before they can be used in the schema definition
  create_enum "status", ['sick', 'on vacation', 'working from home']
end
```

### Actual Schema
```ruby
ActiveRecord::Schema.define(version: 2019_09_27_145140) do
  # ...

  # These are custom enum types that must be created before they can be used in the schema definition
  create_enum "status", %w[sick on vacation working from home]
end
```

This ☝️will lead to the enum being created with values `["sick", "on", "vacation", "working", "from", "home"]`

### PR DESCRIPTION
**Pull request by AndrewSpeed**
# What changed?

This PR:
 * Updates the schema dumper to dump enums with spaces into the `schema.rb` file correctly
 * Updates the adapter to return enum values with comma delimiters
   * It's possible for commas to be present in an enum value, but I'm not sure what we could use as an alternative that can't be included in a value associated with an enum :confused: 
 * Updates specs and fixtures to include coverage for this change

fixes #3

### CODE REVIEW

**Comment by AndrewSpeed** [comment]
I've been experimenting a little with approaches to removing `string_agg` with a delimiter for this PR.

It seems that we could use `array_agg` instead of `string_agg`, however we'd need to parse this using `PG::TextDecoder::Array` for Rails 4.1, which parses this value into `"{\"foo bar\",bar,baz}"`. In subsequent rails versions this gets parsed into `"["foo bar","bar","baz"]`, so wouldn't need decoded.

I'm guessing that to do this we'd have to follow the same pattern as has been taken for the schema dumper and other rails version specific functionality.

@alassek Do you think this is worthwhile doing or are you happy with this PR as is?

**Comment by alassek** [comment]
@AndrewSpeed thanks for the PR, this all looks pretty good to me. I fixed the lockfiles problem in master, so you can drop your second commit and rebase. That was my mistake, it doesn't belong here.

I think I would prefer to switch to `array_agg` like you suggest. I'm poking around right now, and so far I think it should be doable without multiple implementations.

**Comment by AndrewSpeed** [comment]
I'm not sure what just happened here, I rebased against `master`, force pushed and now the PR is closed :confused:

**Comment by alassek** [comment]
@AndrewSpeed sorry for the confusion, I have a working implementation for `enum_types` so I merged this manually.

**Comment by AndrewSpeed** [comment]
Great, thanks very much @alassek 😄

**Pull request closed without merging**
